### ISSUE TITLE
大哥 coze-chat 项目咋没了

### ISSUE THREAD

**Issue by jonntd** [haoxiang6436/music-front#1]

**Comment by haoxiang6436** [comment]
@jonntd 之前token被搞欠费了😭😭我就隐藏了，现在公开了。密钥是coze

**Comment by jonntd** [comment]
> @jonntd 之前token被搞欠费了😭😭我就隐藏了，现在公开了。密钥是coze

免费的感觉就能用100次

**Comment by haoxiang6436** [comment]
@haoxiang6436 我那100次已经清零了😢
